# Backend NestJS
FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .
# Générer le client Prisma
RUN npx prisma generate
RUN npm run build

EXPOSE 3000

# Exécuter les migrations et démarrer l'application
CMD sh -c "npx prisma migrate deploy && node dist/src/main.js"
